name: Deploy packages to test-pypi

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.8.0
          poetry_version: 1.0.2
          args: --help
