name: Deploy packages to test-pypi

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install poetry
      - name: Build package
        run: |
          python tools/bump_post_version.py
          poetry build
      - name: Publish test pypi
        run: |
          poetry config http-basic.testpypi $PYPI_USERNAME $PYPI_PASSWORD 
          poetry publish -r testpypi
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
